### ISSUE TITLE
MQTT Trigger: Missing variable: 'inputs'

### ISSUE THREAD

**Issue by sceptri** [kestra-io/plugin-mqtt#37]
### Expected Behavior

Considering the MWE flow I would expect the input `test` to be filled with default value on the trigger of the flow by an MQTT Trigger. If I use a Schedule trigger, everything works as expected.

### Actual Behaviour

It throws an error that `inputs` variable is missing:
```
2024-02-17T09:15:38.736Z ERROR Missing variable: 'inputs' on '{{ inputs.test }}' at line 1
2024-02-17T09:15:38.736Z ERROR Root attribute [inputs] does not exist or can not be accessed and strict variables is set to true. ({{ inputs.test }}:1)
```

### Steps To Reproduce

1. an MQTT user with the name "kestra" and password "12345" with readwrite permission on `misc/#`
2. publish a message to `misc/comms` with string payload (should be necessary)

### Environment Information

- Kestra Version: 0.14.4
- Plugin version: 0.14.0
- Operating System (OS / Docker / Kubernetes): NixOs 23.11
- Java Version (If not docker): 19

### Example flow
```
id: mqtt_trigger
namespace: tests

inputs:
  - name: test
    type: STRING
    defaults: "I have a default value"

tasks:
  - id: debug
    type: io.kestra.core.tasks.log.Log
    message: "{{ inputs.test }}"

triggers:
  - id: mqtt-from-hass
    type: io.kestra.plugin.mqtt.Trigger
    server: tcp://localhost:1883
    clientId: kestraMqttTest
    qos: 2
    topic:
      - misc/comms
    serdeType: STRING
    username: kestra
    password: "12345"
    interval: PT30S
    maxDuration: PT30S
```

**Comment by loicmathieu** [comment]
Hi,
The `Schedule` has a special treatment that set default inputs into the execution context, that's why it works there.
We'll discuss internally whether we think it's a good idea to also do this for regular poling triggers.
Meanwhile, you can use the [coalesce operator](https://kestra.io/docs/concepts/pebble#coalesce-operator-to-conditionally-use-trigger-or-execution-date).

```yaml
tasks:
  - id: debug
    type: io.kestra.core.tasks.log.Log
    message: "{{ inputs ?? input.test }}"
```
